### ISSUE TITLE
Get a true checkpoint/restart

### ISSUE THREAD

**Issue by ecoon** [amanzi/ats#103]
We have a "nearly" checkpoint/restart capability now, but cannot yet get the restart to have the identical state to if one continued a simulation without restart.

Things that need to be fixed include:

1. Currently with ATS, the first timestep size after restart takes the checkpoint file's dt, but the second timestep takes the "initial time step" instead of letting the solver decide based on the first dt.
2. Need to have PK provide the time integrator with memory for its solution history so that extrapolation in time can guess the new solution.  Once the PK provides the memory, it can put it in state and those "old solutions" can be put into the checkpoint file for restart.

**Comment by ecoon** [comment]
Fixed with merge of new-state

**Comment by lijingwang** [comment]
Hi Ethan, 

I noticed this issue is closed but I am facing similar problems: I start the ATS with a new checkpoint. However, no matter what I specify for the "initial time step" in the PKs, it will always start from 1 second which is a very small step size. I want it starts from 1 day = 86400 second. Is that possible? 

Or does that matter for the actual running? I am facing a very small time step issue and the running is extremely slow. Thanks! 


Best,
Lijing.
