### ISSUE TITLE
Upwinding total flux is wrong for surface flow

### ISSUE THREAD

**Issue by dasvyat** [amanzi/ats#11]
Upwinding works incorrectly, at least total flux option. I didn't check other options yet.
Upwinding is done based on mass_flux direction. The direction is 0 on boundary face.
It results in overland conductivity on boundary face is the half of the cell values.
This is wrong. It may cause several problems but I caught it testing zero gradient BC.

Moreover, the mixture of two approaches lead to confusion. At first, we use "flux"
vector to defined upwind and downwind cells in upwind_total_flux. But then we replace real flux with mass_flux direction. It means one tolerance is replaced by the other. This is very confusing. My suggestion is to use real mass flux for the upwind with small default tolerance.

Additionally, if there is no downwind cells the face value is considered as downwind value. But it is still possible to take an average of downwind and upwind values (in this case cell and face value) which is wrong.

**Comment by ecoon** [comment]
mass_flux_direction is intended to be grad (p) + rho*g*\hat{z}, effectively just q/k_r.  The problem with using flux directly is that it is then the old iterate's flux (obviously we don't know the new iterate's flux yet, as we don't have an upwinded kr yet).  There have been some issues with flipping signs and lagging the flux causing this to get weird answers and nonconvergent behavior.  mass_flux_direction, on the other hand, can be calculated prior to doing upwinding.

**Comment by ecoon** [comment]
This appears to be two distinct bugs:
1. zero gradient issues: the zero gradient calculation uses the matrices, before BC application, to calculate grad z.  But in the case of flux_dir matrices, we were only calling UpdateMatrices() once (because these do not change in time for the flux_dir -- all constant coefficients), then ApplyBCs() many times.  ApplyBCs() overwrites the "shadowed" matrix, so effectively both shadowed and non-shadowed always had 0 in them after the 2nd call to ApplyBCs().  So we need to first call CopyShadowToMaster() to recover the non-BC-applied matrices.

2. Halving of the rel perm value when flux dir is small.  I see this in no-flux cases for sure, may be an issue more generally as Daniil described above.  Still working on this.

**Comment by ecoon** [comment]
The second issue is actually indicative of a different issue -- not really the upwinding.  The issue is that in the case of flux boundary conditions, the boundary face is never actually calculated  -- it is only used in Dirichlet data cases.  This means that on the boundary_face entry on Neumann faces is whatever you initialized it at (often p = p_atm, or h=0) and the resulting conductivity is also 0.  So at least in the case of Neumann, no-flux data, the flux potential is 0, so the upwinded conductivity is the average of the cell value and the face value (which is 0), so the upwinded value is 1/2 the cell value. 

This is a problem for bookkeeping, but not a problem for the solution.  In the Neumann case, we never actually use the conductivity on that face.  I'm changing the code to, on Neumann problems, copy the cell pressure into the boundary face, just so it looks sane.  This will not change any answers, but will make the text output look better.

**Comment by ecoon** [comment]
Note the self-consistent way to deal with this issue is to solve for the boundary face pressure that results in that Neumann flux value.  I would have thought that this was needed in the surface-subsurface coupling case where the surface is brought in through the boundary faces.

Is there an example of this coupling somewhere?  We need to get this in the regression tests, e.g. coupling FV subsurface to FV surface.  I'm not sure that my changes don't break that coupling as it currently stands.  And also update regression tests to include NLFV.

**Comment by ecoon** [comment]
Ok, I have confirmed that the zero gradient test gets the right rel perm now, and that the non-zero gradient but non-zero Neumann data tests (surface_water-bc_critical_depth) do not print conductivities that are half the nominal value, but STILL give the identical cell value (i.e. the change to bookkeeping did not change the solution).  I'm going to commit these changes and do a pull request -- @dasvyat please take a look at the problems you were seeing and see if this makes them go away.

**Comment by ecoon** [comment]
I believe this to be closed and haven't heard otherwise.
