### ISSUE TITLE
Misses by Input File Convertors 

### ISSUE THREAD

**Issue by saubhagya-gatech** [amanzi/ats#241]
Below are some of the misses by input file convertors 1.3->1.4->master

- Duplicate parameter list for `saturation_liquid `
- In the observations lists, `mass_flux` instead of `water_flux`
- In the WRM parameter lists, `WRM type` instead of `WRM Type`
- `relative_humidity` appearing in the observation lists

**Comment by gaobhub** [comment]
"permafrost WRM type" will be detected and fixed in the one PR I submitted.

-----
Regards,
Bo Gao
Technical Professional Staff
Oak Ridge National Laboratory


From: Ethan Coon ***@***.***>
Date: Wednesday, March 6, 2024 at 9:41 AM
To: amanzi/ats ***@***.***>
Cc: Gao, Bo ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [amanzi/ats] Misses by Input File Convertors (Issue #241)

Also, @gaobhub<https://urldefense.us/v2/url?u=https-3A__github.com_gaobhub&d=DwMCaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=z8ZQhSRW0ml12w9lbN1_6Q&m=rgdN9LU6g-bHM-AuXEFZOLnEHASgDQ5jdpEvjS4Z7rBJ7xpe4hxse5CuAlbz4Wli&s=JeIJ390jHN8ULUWhUaUsCCzCCSfYW04mQTtprIZfe7o&e=> can you change "permafrost WRM type" --> "permafrost wrm type" in the converter? I'm doing the code for this today.
