### ISSUE TITLE
Upwind operator may produce inf and nan in output

### ISSUE THREAD

**Issue by dasvyat** [amanzi/ats#42]
ATS upwind operator may produce inf and nan in the output which then pollutes other fields ( fluxes etc) and leads to a crash of the simulation with a confusing explanation message.

**Comment by ecoon** [comment]
I think this is actually two common input file issues, not code issues.

1. If the overland pressure isn't initialized on "boundary_face" entities, then uninitialized data can cause weird behavior.  Note, this is likely not a problem in coupled runs, because "initialize surface head from subsurface" implies to "initialize faces from cells" and so boundary faces are set with this option turned on (which it is for almost all coupled runs).

2. If the manning coefficient isn't initialized on "boundary_face" entities, then the overland conductivity can divide by 0, providing inf in the boundary face overland conductivity.  Note, this is only a problem for Dirichlet, inward-fluxing boundary conditions or seepage face conditions when the flux = 0.  In both of those cases, the 0 Manning coefficient results in inf on the boundary face, which then only affects the runs if it is upwinded onto the face.

In 96611581016269aeccb8cd7c4d1373458d6ec6a9 I added a check in the overland conductivity evaluator for ensuring that the min of Manning's n is > 0.  If not, it provides a better error message to tell the user that they likely forgot to initialize this.

**Comment by ecoon** [comment]
Note that for Elchin's run that ran into this issue, the Manning's n on boundary faces was uninitialized.

We should likely add an option to take Manning's n from the internal cell.  This would be useful especially for doing cases where it is set by "labeled sets" from the mesh (e.g. for land cover data or others) when setting faces values cannot be done so easily.

**Comment by dasvyat** [comment]
Ethan, thank you for clarifying this. Is it possible that ConsistencyCheck would catch this problem? The main difficulty here is that the simulation was running for quite a while with the wrong settings before it crashed.
